

try {
    throw new Error();
}
catch (e) {
    console.error("Error catched, console.error")
}
